name = "chilamboli"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".nuxt/dist"

[[d1_databases]]
binding = "DB"
database_name = "chilamboli-db"
database_id = "bc0afddf-c8be-4842-9757-b4e1ec786526"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "KV"
id = "b0c05dd4200b4984b0741bfdcf1864e7"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "chilamboli"
